title: technical capital
email: vladas.mr@gmail.com
description: >-
  I blog about things I find out for myself and have an urge to share them with the Internet. Maybe someone else will find it useful...

domain: vlmaier.github.io
url: https://vlmaier.github.io
baseurl: ""

# Social networks
github_username: vlmaier
linkedin_username: vladas-maier
rss: rss

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

header_pages:
  - about.md
  - cv.md
